export const SET_CONTACT_FORM_DATA = 'SET_CONTACT_FORM_DATA';
export const RESET_CONTACT_FORM_DATA = 'RESET_CONTACT_FORM_DATA';
export const SET_CONTACT_FORM_ERRORS = 'SET_CONTACT_FORM_ERRORS';
export const RESET_CONTACT_FORM_ERRORS = 'RESET_CONTACT_FORM_ERRORS';
